/** @type {import('tailwindcss').Config} */
export default {
	darkMode: 'class',
	content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
	theme: {
		extend: {
			colors: {
				'surface-tint': '#ffb59a',
				'inverse-on-surface': '#313030',
				'surface-container': '#201f1f',
				'surface-dim': '#131313',
				'primary-fixed': '#ffdbce',
				'on-error': '#690005',
				'surface-container-low': '#1c1b1b',
				'on-primary': '#5a1b00',
				'on-background': '#e5e2e1',
				background: '#131313',
				'inverse-primary': '#a73a00',
				'surface-container-high': '#2a2a2a',
				'on-primary-fixed-variant': '#802a00',
				'on-surface-variant': '#e4beb1',
				primary: '#ffb59a',
				'primary-fixed-dim': '#ffb59a',
				'on-surface': '#e5e2e1',
				'error-container': '#93000a',
				tertiary: '#c8c6c5',
				error: '#ffb4ab',
				'secondary-container': '#454747',
				'on-primary-fixed': '#370e00',
				'outline-variant': '#5b4137',
				'primary-container': '#ff5c00',
				'on-primary-container': '#521800',
				'on-secondary-container': '#b4b5b5',
				'surface-container-lowest': '#0e0e0e',
				'on-tertiary-container': '#2c2b2b',
				'inverse-surface': '#e5e2e1',
				'secondary-fixed-dim': '#c6c6c7',
				'surface-variant': '#353534',
				'surface-bright': '#3a3939',
				'on-secondary-fixed': '#1a1c1c',
				surface: '#131313',
				'on-tertiary': '#313030',
				'tertiary-fixed': '#e5e2e1',
				'on-tertiary-fixed': '#1c1b1b',
				'secondary-fixed': '#e2e2e2',
				'on-secondary-fixed-variant': '#454747',
				'tertiary-container': '#949292',
				'on-error-container': '#ffdad6',
				secondary: '#c6c6c7',
				'tertiary-fixed-dim': '#c8c6c5',
				'on-tertiary-fixed-variant': '#474746',
				'on-secondary': '#2f3131',
				outline: '#ab897d',
				'surface-container-highest': '#353534',
			},
			borderRadius: {
				DEFAULT: '0.25rem',
				lg: '0.5rem',
				xl: '0.75rem',
				full: '9999px',
			},
			spacing: {
				gutter: '24px',
				'section-gap': '120px',
				'container-max': '1280px',
				base: '8px',
				margin: '32px',
			},
			fontFamily: {
				'space-grotesk': ['Space Grotesk', 'sans-serif'],
				inter: ['Inter', 'sans-serif'],
			},
			fontSize: {
				'headline-xl': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
				'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
				'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '500' }],
				'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
				'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
				'headline-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
			},
		},
	},
	plugins: [],
};
